variable "origin_domain_name" {
  description = "The origin's domain name (Wasabi endpoint)"
  type        = string
  default     = "s3.wasabisys.com"
}

variable "origin_path" {
  description = "The origin path to append to the domain name"
  type        = string
  default     = "/khangstoragetest"
}

variable "lambda_edge_secret" {
  description = "Secret used to sign the cookie generated by CloudFront"
  type        = string
  default = "SECRET!"
}

variable "bucket_secret_referer" {
  description = "Secret used to sign the cookie generated by CloudFront"
  type        = string
  default = "SECRET!"
}

variable "region" {
  description = "AWS region to deploy resources"
  type        = string
  default     = "us-east-1"
}

# VPC Variables
variable "project_name" {
  description = "Name of the project for resource naming"
  type        = string
  default     = "APPLICATION_NAME"
}

variable "vpc_cidr" {
  description = "CIDR block for the VPC"
  type        = string
  default     = "10.0.0.0/16"
}

variable "public_subnet_cidrs" {
  description = "List of CIDR blocks for the public subnets"
  type        = list(string)
  default     = ["10.0.1.0/24", "10.0.2.0/24"]
}

variable "private_subnet_cidr" {
  description = "CIDR block for the private subnet"
  type        = string
  default     = "10.0.3.0/24"
}

# EC2 Variables
variable "instance_type" {
  description = "EC2 instance type (free tier eligible: t2.micro)"
  type        = string
  default     = "t2.micro"
}

variable "associate_public_ip" {
  description = "Whether to associate an Elastic IP with the EC2 instance"
  type        = bool
  default     = true
}

variable "aws_region" {
  description = "AWS region for resources"
  type        = string
  default     = "us-east-1"
}

variable "environment_variables" {
  description = "Environment variables for the container"
  type = list(object({
    name  = string
    value = string
  }))
  default = [
    {
      name  = "ASPNETCORE_ENVIRONMENT"
      value = "Production"
    },
    {
      name  = "DATABASE_HOST"
      value = "something.aivencloud.com"
    },
    {
      name  = "DATABASE_PORT"
      value = "16026"
    },
    {
      name  = "DATABASE_NAME"
      value = "defaultdb"
    },
    {
      name  = "DATABASE_USERNAME"
      value = "avnadmin"
    },
    {
      name  = "DATABASE_PASSWORD"
      value = "YOUR_PASSWORD"
    },
    {
      name  = "ASPNETCORE_URLS"
      value = "http://0.0.0.0:5001"
    },
    {
      name  = "RABBITMQ_URL"
      value = "amqps://something.cloudamqp"
    },
    {
      name  = "RABBITMQ_HOST"
      value = "rabbit-mq"
    },
    {
      name  = "RABBITMQ_PORT"
      value = "5672"
    },
    {
      name  = "RABBITMQ_USERNAME"
      value = "rabbitmq"
    },
    {
      name  = "RABBITMQ_PASSWORD"
      value = "YOUR_PASSWORD"
    },
    {
      name  = "REDIS_HOST"
      value = "something.redis-cloud.com"
    },
    {
      name  = "REDIS_PASSWORD"
      value = "YOUR_PASSWORD"
    },
    {
      name  = "REDIS_PORT"
      value = "11762"
    }
  ]
}

variable "enable_auto_scaling" {
  description = "Enable auto scaling for the ECS service"
  type        = bool
  default     = false
}

variable "enable_service_discovery" {
  description = "Enable service discovery"
  type        = bool
  default     = false
}
