variable "origin_domain_name" {
  description = "The origin's domain name (Wasabi endpoint)"
  type        = string
  default     = "s3.wasabisys.com"
}

variable "origin_path" {
  description = "The origin path to append to the domain name"
  type        = string
  default     = "/khangstoragetest"
}

variable "lambda_edge_secret" {
  description = "Secret used to sign the cookie generated by CloudFront"
  type        = string
  default     = "password!"
}

variable "bucket_secret_referer" {
  description = "Secret used to sign the cookie generated by CloudFront"
  type        = string
  default     = "password must same in wasaby or s3 configuration!"
}

variable "region" {
  description = "AWS region to deploy resources"
  type        = string
  default     = "us-east-1"
}

# VPC Variables
variable "project_name" {
  description = "Name of the project for resource naming"
  type        = string
  default     = "projectname"
}

variable "vpc_cidr" {
  description = "CIDR block for the VPC"
  type        = string
  default     = "10.0.0.0/16"
}

variable "public_subnet_cidrs" {
  description = "List of CIDR blocks for the public subnets"
  type        = list(string)
  default     = ["10.0.1.0/24", "10.0.2.0/24"]
}

variable "private_subnet_cidr" {
  description = "CIDR block for the private subnet"
  type        = string
  default     = "10.0.3.0/24"
}

# EC2 Variables
variable "instance_type" {
  description = "EC2 instance type (free tier eligible: t2.micro)"
  type        = string
  default     = "t2.micro"
}

variable "associate_public_ip" {
  description = "Whether to associate an Elastic IP with the EC2 instance"
  type        = bool
  default     = true
}

variable "aws_region" {
  description = "AWS region for resources"
  type        = string
  default     = "us-east-1"
}

# ECS Global Variables
variable "enable_auto_scaling" {
  description = "Enable auto scaling for the ECS service"
  type        = bool
  default     = false
}

variable "enable_service_discovery" {
  description = "Enable service discovery for ECS services"
  type        = bool
  default     = false
}

# Service Definitions Variable
variable "services" {
  description = "Configuration for each microservice"
  type = map(object({
    # ALB Target Group attributes
    alb_target_group_port     = number
    alb_target_group_protocol = string
    alb_target_group_type     = string
    alb_health_check = object({
      enabled             = bool
      path                = string
      port                = string
      protocol            = string
      matcher             = string
      interval            = number
      timeout             = number
      healthy_threshold   = number
      unhealthy_threshold = number
    })

    # ALB Listener Rule attributes
    alb_listener_rule_priority   = number
    alb_listener_rule_conditions = list(object({
      path_pattern = optional(object({
        values = list(string)
      }))
      # Add other condition types here if needed (e.g., host_header)
    }))

    # ECS Container attributes
    ecs_container_name_suffix          = string # e.g. "microservice" to form "project-key-suffix"
    ecs_container_image_repository_url = string
    ecs_container_image_tag            = string
    ecs_container_cpu                  = number
    ecs_container_memory               = number
    ecs_container_essential            = bool
    ecs_container_port_mappings = list(object({
      container_port = number
      host_port      = number
      protocol       = string
    }))
    ecs_environment_variables = list(object({
      name  = string
      value = string
    }))
    ecs_container_health_check = object({
      command     = list(string)
      interval    = number
      timeout     = number
      retries     = number
      startPeriod = number
    })
    ecs_service_discovery_port = number # Port for service discovery registration
  }))
  default = {
    "guest" = {
      alb_target_group_port     = 5001
      alb_target_group_protocol = "HTTP"
      alb_target_group_type     = "instance"
      alb_health_check = {
        enabled             = true
        path                = "/api/guest/health"
        port                = "traffic-port"
        protocol            = "HTTP"
        matcher             = "200"
        interval            = 30
        timeout             = 5
        healthy_threshold   = 2
        unhealthy_threshold = 3
      }
      alb_listener_rule_priority = 10
      alb_listener_rule_conditions = [
        {
          path_pattern = {
            values = ["/api/guest/*"]
          }
        }
      ]
      ecs_container_name_suffix          = "microservice"
      ecs_container_image_repository_url = "something.dkr.ecr.us-east-1.amazonaws.com/goodmeal-ecr"
      ecs_container_image_tag            = "Guest.Microservice-latest"
      ecs_container_cpu                  = 400
      ecs_container_memory               = 400
      ecs_container_essential            = true
      ecs_container_port_mappings = [
        {
          container_port = 5001
          host_port      = 0
          protocol       = "tcp"
        }
      ]
      ecs_environment_variables = [
        { name = "ASPNETCORE_ENVIRONMENT", value = "Production" },
        { name = "DATABASE_HOST", value = "" },
        { name = "DATABASE_PORT", value = "" },
        { name = "DATABASE_NAME", value = "" },
        { name = "DATABASE_USERNAME", value = "" },
        { name = "DATABASE_PASSWORD", value = "" },
        { name = "ASPNETCORE_URLS", value = "http://0.0.0.0:5001" },
        { name = "RABBITMQ_URL", value = "amqps://cloudrabbitmq@leopard.lmq.cloudamqp.com/xcjmxyuo" },
        { name = "RABBITMQ_HOST", value = "" },
        { name = "RABBITMQ_PORT", value = "" },
        { name = "RABBITMQ_USERNAME", value = "" },
        { name = "RABBITMQ_PASSWORD", value = "" },
        { name = "REDIS_HOST", value = "redis-cloud.com" },
        { name = "REDIS_PASSWORD", value = "" },
        { name = "REDIS_PORT", value = "" }
      ]
      ecs_container_health_check = {
        command     = ["CMD-SHELL", "curl -f http://localhost:5001/api/guest/health || exit 1"]
        interval    = 30
        timeout     = 5
        retries     = 3
        startPeriod = 0
      }
      ecs_service_discovery_port = 5001
    },
    "user" = {
      alb_target_group_port     = 5002
      alb_target_group_protocol = "HTTP"
      alb_target_group_type     = "instance"
      alb_health_check = {
        enabled             = true
        path                = "/api/user/health"
        port                = "traffic-port"
        protocol            = "HTTP"
        matcher             = "200"
        interval            = 30
        timeout             = 5
        healthy_threshold   = 2
        unhealthy_threshold = 3
      }
      alb_listener_rule_priority = 11
      alb_listener_rule_conditions = [
        {
          path_pattern = {
            values = ["/api/user/*"]
          }
        }
      ]
      ecs_container_name_suffix          = "microservice"
      ecs_container_image_repository_url = "something.dkr.ecr.us-east-1.amazonaws.com/goodmeal-ecr"
      ecs_container_image_tag            = "User.Microservice-latest"
      ecs_container_cpu                  = 400
      ecs_container_memory               = 400
      ecs_container_essential            = true
      ecs_container_port_mappings = [
        {
          container_port = 5002
          host_port      = 0
          protocol       = "tcp"
        }
      ]
      ecs_environment_variables = [
        { name = "ASPNETCORE_ENVIRONMENT", value = "Production" },
        { name = "DATABASE_HOST", value = "" },
        { name = "DATABASE_PORT", value = "" },
        { name = "DATABASE_NAME", value = "" },
        { name = "DATABASE_USERNAME", value = "" },
        { name = "DATABASE_PASSWORD", value = "" },
        { name = "ASPNETCORE_URLS", value = "http://0.0.0.0:5002" },
        { name = "RABBITMQ_URL", value = "amqps://cloudrabbitmq@leopard.lmq.cloudamqp.com/xcjmxyuo" },
        { name = "RABBITMQ_HOST", value = "" },
        { name = "RABBITMQ_PORT", value = "" },
        { name = "RABBITMQ_USERNAME", value = "" },
        { name = "RABBITMQ_PASSWORD", value = "" },
        { name = "REDIS_HOST", value = "redis-cloud.com" },
        { name = "REDIS_PASSWORD", value = "" },
        { name = "REDIS_PORT", value = "" }
      ]
      ecs_container_health_check = {
        command     = ["CMD-SHELL", "curl -f http://localhost:5002/api/user/health || exit 1"]
        interval    = 30
        timeout     = 5
        retries     = 3
        startPeriod = 0
      }
      ecs_service_discovery_port = 5002
    }
  }
}